name: "Terraform Deploy Reusable Workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to (e.g., dev, prod)"
        required: true
        type: string
    secrets:
      azure_credentials:
        description: "Azure Credentials for authentication"
        required: true
      azure_client_secret:
        description: "Azure Client Secret for authentication"
        required: true
      azure_client_id:
        description: "Azure Client ID for authentication"
        required: true
      spn_config:
        description: "SPN configuration for the deployment"
        required: true

jobs:
  terraform-plan:
    name: "Terraform Plan to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: terraform
    env:
      ARM_CLIENT_ID: ${{ secrets.azure_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      TF_VAR_spn: ${{ secrets.spn_config }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure with Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7.0"

      - name: Copy environment tfvars
        run: |
          cp env/${{ inputs.environment }}.auto.tfvars ./

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["terraform/backend.tf", "terraform/${{ inputs.environment }}.auto.tfvars"]'
        env:
          backendStorageAccount: ${{ vars.BACKEND_STORAGE_ACCOUNT }}
          environment: ${{ inputs.environment }}
          subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          azureTenantId: ${{ vars.AZURE_TENANT_ID }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform deployment
        run: terraform plan -out=tf-plan-${{ inputs.environment }}.tfplan

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-${{ inputs.environment }}.tfplan
          path: terraform/tf-plan-${{ inputs.environment }}.tfplan

  terraform-apply:
    name: "Terraform Apply to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: ${{ inputs.environment }}-approve
    defaults:
      run:
        working-directory: terraform
    outputs:
      sql_fqdn: ${{ steps.tf_output.outputs.sql_fqdn }}
      sql_db: ${{ steps.tf_output.outputs.sql_db }}
      app_principal_id: ${{ steps.tf_output.outputs.app_principal_id }}
      sql_principal_id: ${{ steps.tf_output.outputs.sql_principal_id }}
    env:
      ARM_CLIENT_ID: ${{ secrets.azure_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      TF_VAR_spn: ${{ secrets.spn_config }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7.0"

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: "terraform/backend.tf"
        env:
          backendStorageAccount: ${{ vars.BACKEND_STORAGE_ACCOUNT }}
        
      - name: Initialize Terraform
        run: terraform init

      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-${{ inputs.environment }}.tfplan
          path: terraform

      - name: Apply Terraform deployment
        run: terraform apply -auto-approve tf-plan-${{ inputs.environment }}.tfplan

      - name: Get Terraform output
        id: tf_output
        run: |
          terraform output -json
          bash ../scripts/query_tf_outputs.sh

  setup-database:
    name: "Setup Database User - ${{ inputs.environment }}"
    runs-on: windows-latest
    needs: terraform-apply
    environment: ${{ inputs.environment }}
    env:
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.azure_client_id }}
      AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure with Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Add user to database
        env:
          SQL_FQDN: ${{ needs.terraform-apply.outputs.sql_fqdn }}
          SQL_DB: ${{ needs.terraform-apply.outputs.sql_db }}
          APP_PRINCIPAL_ID: ${{ needs.terraform-apply.outputs.app_principal_id }}
          SQL_PRINCIPAL_ID: ${{ needs.terraform-apply.outputs.sql_principal_id }}

        run: powershell -File ./scripts/create_or_update_db_user.ps1
